theme: jekyll-theme-cayman

# Name of website
title: Personal Projects

# Short description of the site
description: Ismael Serrano Loba

# Your name to show in the footer
author: Ismael Serrano Loba





