theme: jekyll-theme-cayman

# Name of website
title: Ismael Serrano

# Short description of the site
description: A brief portfolio of projects

# Your name to show in the footer
author: Ismael Serrano Loba




