theme: jekyll-theme-cayman

# Name of website
title: Ismael Serrano

# Short description of the site
description: Personal Projects

# Your name to show in the footer
author: Ismael Serrano Loba

#defaults:
# -
 ##  scope:
    # path:""
  # values:  
       #theme: minima




